CREATE TABLE IF NOT EXISTS `document3` (
  `id` int(11) NOT NULL,
  `day` int(2) unsigned zerofill NOT NULL,
  `month` int(2) unsigned zerofill NOT NULL,
  `year` int(2) NOT NULL,
  `firstname1` varchar(32) NOT NULL,
  `lastname1` varchar(32) NOT NULL,
  `firstname` varchar(32) NOT NULL,
  `lastname` varchar(32) NOT NULL,
  `idnumber` varchar(32) NOT NULL,
  `phone` varchar(32) NOT NULL,
  `email` varchar(32) NOT NULL,
  `make` varchar(32) NOT NULL,
  `type` varchar(32) NOT NULL,
  `model` varchar(32) NOT NULL,
  `license` varchar(32) NOT NULL,
  `mileage` int(6) NOT NULL,
  `m1_el1` int(1) NOT NULL,
  `m1_el2` int(1) NOT NULL,
  `m1_el3` int(1) NOT NULL,
  `m1_el4` int(1) NOT NULL,
  `m1_el5` int(1) NOT NULL,
  `m1_el6` int(1) NOT NULL,
  `m1_el7` int(1) NOT NULL,
  `m1_el8` int(1) NOT NULL,
  `m1_el9` int(1) NOT NULL,
  `m1_el10` int(1) NOT NULL,
  `m1_el11` int(1) NOT NULL,
  `m1_el12` int(1) NOT NULL,
  `m2_el1` int(1) NOT NULL,
  `m2_el2` int(1) NOT NULL,
  `m3_el1` int(1) NOT NULL,
  `m3_el2` int(1) NOT NULL,
  `m3_el3` int(1) NOT NULL,
  `m3_el4` int(1) NOT NULL,
  `m4_el1` int(1) NOT NULL,
  `m4_el2` int(1) NOT NULL,
  `m4_el3` int(1) NOT NULL,
  `m4_el4` int(1) NOT NULL,
  `m4_el5` int(1) NOT NULL,
  `m4_el6` int(1) NOT NULL,
  `m4_el7` int(1) NOT NULL,
  `m4_el8` int(1) NOT NULL,
  `m4_el9` int(1) NOT NULL,
  `m4_el10` int(1) NOT NULL,
  `m5_el1` int(1) NOT NULL,
  `m5_el2` int(1) NOT NULL,
  `m5_el3` int(1) NOT NULL,
  `m5_el4` int(1) NOT NULL,
  `m5_el5` int(1) NOT NULL,
  `m5_el6` int(1) NOT NULL,
  `m6_el1` int(1) NOT NULL,
  `m6_el2` int(1) NOT NULL,
  `m6_el3` int(1) NOT NULL,
  `m6_el4` int(1) NOT NULL,
  `m6_el5` int(1) NOT NULL,
  `m7_el1` int(1) NOT NULL,
  `m7_el2` int(1) NOT NULL,
  `m7_el3` int(1) NOT NULL,
  `m7_el4` int(1) NOT NULL,
  `m8_el1` int(1) NOT NULL,
  `m8_el2` int(1) NOT NULL,
  `m9_el1` int(1) NOT NULL,
  `m9_el2` int(1) NOT NULL,
  `m9_el3` int(1) NOT NULL,
  `m9_el4` int(1) NOT NULL,
  `m9_el5` int(1) NOT NULL,
  `m10_el1` int(1) NOT NULL,
  `m10_el2` int(1) NOT NULL,
  `m10_el3` int(1) NOT NULL,
  `m10_el4` int(1) NOT NULL,
  `m10_el5` int(1) NOT NULL,
  `m11_el1` int(1) NOT NULL,
  `m11_el2` int(1) NOT NULL,
  `m11_el3` int(1) NOT NULL,
  `comment1` varchar(500) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `comment2` varchar(500) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `comment3` varchar(500) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `comment4` varchar(500) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `comment5` varchar(500) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `signature` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `sig_hash` varchar(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `ip` varchar(46) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `created` int(11) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

